// Generated by GraphWalker (http://www.graphwalker.org)
package vvs.AutoEstado;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "vvs/AutoEstado/Estados.graphml")
public interface Estados {

    @Edge()
    void activar();

    @Edge()
    void evacuar();

    @Vertex()
    void Activa();

    @Edge()
    void cerrar();

    @Vertex()
    void Evacuacion();

    @Vertex()
    void Cerrada();

    @Edge()
    void mantenimiento();

    @Vertex()
    void Mantenimiento();
}
