// Generated by GraphWalker (http://www.graphwalker.org)
package vvs.AutoEstado;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

/**
 * The Interface Estados.
 */
@Model(file = "vvs/AutoEstado/Estados.graphml")
public interface Estados {

    /**
     * Activar.
     */
    @Edge()
    void activar();

    /**
     * Evacuar.
     */
    @Edge()
    void evacuar();

    /**
     * Activa.
     */
    @Vertex()
    void Activa();

    /**
     * Crear piscina.
     */
    @Edge()
    void crearPiscina();

    /**
     * Cerrar.
     */
    @Edge()
    void cerrar();

    /**
     * Evacuacion.
     */
    @Vertex()
    void Evacuacion();

    /**
     * Cerrada.
     */
    @Vertex()
    void Cerrada();

    /**
     * Mantenimiento.
     */
    @Edge()
    void mantenimiento();

    /**
     * Mantenimiento.
     */
    @Vertex()
    void Mantenimiento();
}
